[project]
name = "nth-roots-of-unity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "manim>=0.19.0",
    "sympy>=1.13.3",
]
